### ISSUE TITLE
Reading multiple properties in a single step

### ISSUE THREAD

**Issue by altrisi** [christian-draeger/read-properties#2]
I don't know how viable this is, but it can be quite tedious to have one step per property, mostly when you have to read multiple properties from a single file.

Would it be possible to pass an array (or something similar that is supported) to the `property` field instead and then get every result in its own output, like `${{steps.stepid.outputs.propertyname}}`?

**Comment by RubixDev** [comment]
While we wait for the PR to be merged, my fork can be used with `uses: RubixDev/read-properties@v1`

**Comment by christian-draeger** [comment]
Released as version 1.1.0
