### ISSUE TITLE
set-output deprecated

### ISSUE THREAD

**Issue by mandrachek** [christian-draeger/read-properties#8]
Using 1.1.0, I'm getting

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by mandrachek** [comment]
I see this is fixed on release 1.1.1 - looks like the readme is out of date (still has 1.1.0)

**Comment by christian-draeger** [comment]
oh yeah you are right. thanks for pointing this out, i changed the readme
